### ISSUE TITLE
Cannot create partial view that contains '-' in its name

### ISSUE THREAD

**Issue by GiorgosBetsos** [mvelosop/AspNetCore2CoreUI#4]
Trying to create a new partial view named, e.g., **_app-myview**, fails. However you can temporarily name the view to e.g. **_AppMyView** and then rename it to **_app-myview**.

Steps to reproduce: 

1. Open AspNetCore21CoreUI2.sln in Visual Studio Community 2017 v. 15.7.5
2. Create a partial view in Views/Shared (_Create as a partial view_ checkbox checked)
3. Creating the view file fails. A screen-shot of the error message is attached.

![create partial view](https://user-images.githubusercontent.com/18726683/42752424-85330ef2-88f6-11e8-8655-8c720a2b65f5.png)

![error message](https://user-images.githubusercontent.com/18726683/42752440-93514cc4-88f6-11e8-8319-f6b675fff517.png)

**Comment by mvelosop** [comment]
Hi Giorgos,

I could see the error about the dash in the partial view name! I hadn't realized that, because I didn't create the partial views that way, I copied the html files from CoreUI and then renamed them.

On the other hand, since partial views basically start as an empty file, I usually create them with [Shift]+[F2] (from extension [Add New File](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.AddNewFile))

Regarding the Index view broken, the one in your repo is definitely broken, and it's also different from the original repo. I recommend having [Beyond Compare](https://www.scootersoftware.com) or similar in your toolkit, which is great to pinpoint situations like this.

Hope this helps.
